package persistencias;
// Generated 6 feb 2023 20:24:59 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista implements java.io.Serializable {

	private String dni;
	private String nombre;
	private String apellidos;
	private Integer telefono;
	private String nombreCancion;
	private Set resultadosEdads = new HashSet(0);
	private Set resultadosComunidads = new HashSet(0);

	public Artista() {
	}

	public Artista(String dni, String nombre, String apellidos) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Artista(String dni, String nombre, String apellidos, Integer telefono, String nombreCancion,
			Set resultadosEdads, Set resultadosComunidads) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.nombreCancion = nombreCancion;
		this.resultadosEdads = resultadosEdads;
		this.resultadosComunidads = resultadosComunidads;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getNombreCancion() {
		return this.nombreCancion;
	}

	public void setNombreCancion(String nombreCancion) {
		this.nombreCancion = nombreCancion;
	}

	public Set getResultadosEdads() {
		return this.resultadosEdads;
	}

	public void setResultadosEdads(Set resultadosEdads) {
		this.resultadosEdads = resultadosEdads;
	}

	public Set getResultadosComunidads() {
		return this.resultadosComunidads;
	}

	public void setResultadosComunidads(Set resultadosComunidads) {
		this.resultadosComunidads = resultadosComunidads;
	}

}
