package persistencias;
// Generated 6 feb 2023 20:24:59 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;

/**
 * PorcentajeVotacionRango generated by hbm2java
 */
public class PorcentajeVotacionRango implements java.io.Serializable {

	private String rango;
	private BigDecimal porcentaje;

	public PorcentajeVotacionRango() {
	}

	public PorcentajeVotacionRango(String rango) {
		this.rango = rango;
	}

	public PorcentajeVotacionRango(String rango, BigDecimal porcentaje) {
		this.rango = rango;
		this.porcentaje = porcentaje;
	}

	public String getRango() {
		return this.rango;
	}

	public void setRango(String rango) {
		this.rango = rango;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
