package persistencias;
// Generated 10 feb 2023 0:50:55 by Hibernate Tools 5.4.33.Final

/**
 * ResultadosComunidad generated by hbm2java
 */
public class ResultadosComunidad implements java.io.Serializable {

	private int idResultadoComunidad;
	private Artista artista;
	private String nombreComunidad;
	private Integer numeroVotosComunidad;

	public ResultadosComunidad() {
	}

	public ResultadosComunidad(int idResultadoComunidad, String nombreComunidad) {
		this.idResultadoComunidad = idResultadoComunidad;
		this.nombreComunidad = nombreComunidad;
	}

	public ResultadosComunidad(int idResultadoComunidad, Artista artista, String nombreComunidad,
			Integer numeroVotosComunidad) {
		this.idResultadoComunidad = idResultadoComunidad;
		this.artista = artista;
		this.nombreComunidad = nombreComunidad;
		this.numeroVotosComunidad = numeroVotosComunidad;
	}

	public int getIdResultadoComunidad() {
		return this.idResultadoComunidad;
	}

	public void setIdResultadoComunidad(int idResultadoComunidad) {
		this.idResultadoComunidad = idResultadoComunidad;
	}

	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	public String getNombreComunidad() {
		return this.nombreComunidad;
	}

	public void setNombreComunidad(String nombreComunidad) {
		this.nombreComunidad = nombreComunidad;
	}

	public Integer getNumeroVotosComunidad() {
		return this.numeroVotosComunidad;
	}

	public void setNumeroVotosComunidad(Integer numeroVotosComunidad) {
		this.numeroVotosComunidad = numeroVotosComunidad;
	}

}
