package persistencias;
// Generated 10 feb 2023 0:50:55 by Hibernate Tools 5.4.33.Final

/**
 * ResultadosEdad generated by hbm2java
 */
public class ResultadosEdad implements java.io.Serializable {

	private Integer idResultadoEdad;
	private Artista artista;
	private String rango;
	private Integer numeroVotosEdad;

	public ResultadosEdad() {
	}

	public ResultadosEdad(String rango) {
		this.rango = rango;
	}

	public ResultadosEdad(Artista artista, String rango, Integer numeroVotosEdad) {
		this.artista = artista;
		this.rango = rango;
		this.numeroVotosEdad = numeroVotosEdad;
	}

	public Integer getIdResultadoEdad() {
		return this.idResultadoEdad;
	}

	public void setIdResultadoEdad(Integer idResultadoEdad) {
		this.idResultadoEdad = idResultadoEdad;
	}

	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	public String getRango() {
		return this.rango;
	}

	public void setRango(String rango) {
		this.rango = rango;
	}

	public Integer getNumeroVotosEdad() {
		return this.numeroVotosEdad;
	}

	public void setNumeroVotosEdad(Integer numeroVotosEdad) {
		this.numeroVotosEdad = numeroVotosEdad;
	}

}
