package persistencias;
// Generated 6 feb 2023 20:24:59 by Hibernate Tools 5.4.33.Final

/**
 * ResultadosGenerales generated by hbm2java
 */
public class ResultadosGenerales implements java.io.Serializable {

	private String dniArtista;
	private Integer votosTotales;

	public ResultadosGenerales() {
	}

	public ResultadosGenerales(String dniArtista) {
		this.dniArtista = dniArtista;
	}

	public ResultadosGenerales(String dniArtista, Integer votosTotales) {
		this.dniArtista = dniArtista;
		this.votosTotales = votosTotales;
	}

	public String getDniArtista() {
		return this.dniArtista;
	}

	public void setDniArtista(String dniArtista) {
		this.dniArtista = dniArtista;
	}

	public Integer getVotosTotales() {
		return this.votosTotales;
	}

	public void setVotosTotales(Integer votosTotales) {
		this.votosTotales = votosTotales;
	}

}
