package persistencias;
// Generated 6 feb 2023 20:24:59 by Hibernate Tools 5.4.33.Final

/**
 * ResultadosEdad generated by hbm2java
 */
public class ResultadosEdad implements java.io.Serializable {

	private String rango;
	private Artista artista;
	private Integer numeroVotosEdad;

	public ResultadosEdad() {
	}

	public ResultadosEdad(String rango) {
		this.rango = rango;
	}

	public ResultadosEdad(String rango, Artista artista, Integer numeroVotosEdad) {
		this.rango = rango;
		this.artista = artista;
		this.numeroVotosEdad = numeroVotosEdad;
	}

	public String getRango() {
		return this.rango;
	}

	public void setRango(String rango) {
		this.rango = rango;
	}

	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	public Integer getNumeroVotosEdad() {
		return this.numeroVotosEdad;
	}

	public void setNumeroVotosEdad(Integer numeroVotosEdad) {
		this.numeroVotosEdad = numeroVotosEdad;
	}

}
