package persistencias;
// Generated 6 feb 2023 20:24:59 by Hibernate Tools 5.4.33.Final

/**
 * ResultadosComunidad generated by hbm2java
 */
public class ResultadosComunidad implements java.io.Serializable {

	private String nombreComunidad;
	private Artista artista;
	private Integer numeroVotosComunidad;

	public ResultadosComunidad() {
	}

	public ResultadosComunidad(String nombreComunidad) {
		this.nombreComunidad = nombreComunidad;
	}

	public ResultadosComunidad(String nombreComunidad, Artista artista, Integer numeroVotosComunidad) {
		this.nombreComunidad = nombreComunidad;
		this.artista = artista;
		this.numeroVotosComunidad = numeroVotosComunidad;
	}

	public String getNombreComunidad() {
		return this.nombreComunidad;
	}

	public void setNombreComunidad(String nombreComunidad) {
		this.nombreComunidad = nombreComunidad;
	}

	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	public Integer getNumeroVotosComunidad() {
		return this.numeroVotosComunidad;
	}

	public void setNumeroVotosComunidad(Integer numeroVotosComunidad) {
		this.numeroVotosComunidad = numeroVotosComunidad;
	}

}
